# Fill and rename this file to 'config.yml'

query: ""
start_date: "2022-04-23 00:00:00+00:00"                 # "yyyy-mm-dd hh:mm:ss+hh:mm"
end_date: "2022-07-19 00:00:00+00:00"
interval_days : 1

bearer_token: ""

project_id: ""
dataset: ""

user_email: ""

DATA: True
TCAT: False
TweetQuery: False
