# Fill and rename this file to 'config.yml'

query: '((Depp OR "Amber Heard" OR AmberHeard OR IStandWithHeard OR IStandWithAmber OR JusticeForAmber OR JusticeForHeard OR TeamAmber OR TeamHeard OR AmberTurd OR MenToo) OR (johnny amber) OR (johnny heard) OR "mentoo") la
ng:en'
                                                        # OR a list of search strings (up to 1024 characters each) e.g. ['cats OR kittens', 'dogs OR puppies', 'birds chicks from:albomp']

start_date: '2022-04-04 00:00:00+00:00'                 # "yyyy-mm-dd hh:mm:ss+hh:mm"
end_date: '2022-06-08 00:00:00+00:00'                   # "yyyy-mm-dd hh:mm:ss+hh:mm"

bearer_token: 'AAAAAAAAAAAAAAAAAAAAAJI9iwEAAAAAjP%2BZnNxkjCZG4iD%2B2oi30mJ2%2B5I%3Dh4bRZUA9DfLgKE2EztwmJHf02Dx3JqWYQjHxJgiHZ60HSMEktZ'    # your Twitter Academic API bearer token

project_id: 'dmrc-platforms'                                   # Billing project
dataset: 'misogyny_depp'                                      # Desired dataset name

DATA: True
TCAT: False
TweetQuery: False

local_json_only: True      # defaults to False. Setting this to True will skip steps after saving the JSON files to local disk.


