# Fill and rename this file to 'config.yml'

query: 'string'                                         # Search string (up to 1024 characters)

start_date: '2022-04-23 00:00:00+00:00'                 # "yyyy-mm-dd hh:mm:ss+hh:mm"
end_date: '2022-07-19 00:00:00+00:00'                   # "yyyy-mm-dd hh:mm:ss+hh:mm"

bearer_token: ''                                        # your Twitter Academic API beaerer token

project_id: 'project'                                   # Billing project
dataset: 'dataset'                                      # Desired dataset name

DATA: True
TCAT: False
TweetQuery: False
